adapter: postgresql
host: 172.30.96.31                      # VM IP    
port: 5432                    # VM Port   
database: sampledb         # Database Name    
username: user8JX            # User Name    
password: 'BwgloXRiI8y3jGco'            # Password  
