adapter: postgresql
host: <host>                      # VM IP    
port: <port>                      # VM Port   
database: <database name>         # Database Name    
username: <user_name>             # User Name    
password: '<password>'            # Password  
